// src/permission/action.enum.ts

export enum Action {
  // Broad Banner
  UPDATE_BROAD_BANNER = 'UPDATE_BROAD_BANNER',
  CREATE_BROAD_BANNER = 'CREATE_BROAD_BANNER',
  DELETE_BROAD_BANNER = 'DELETE_BROAD_BANNER',

  // seasonal categories
  SEASONAL_CATEGORY_DELETE = 'SEASONAL_CATEGORY_DELETE',
  SEASONAL_CATEGORY_CREATE = 'SEASONAL_CATEGORY_CREATE',
  SEASONAL_CATEGORY_UPDATE = 'SEASONAL_CATEGORY_UPDATE',
  SEASONAL_CATEGORY_REORDER = 'SEASONAL_CATEGORY_REORDER',

  // seasonal categories
  HOMEPAGE_GALLERY_UPDATE = 'HOMEPAGE_GALLERY_UPDATE',
  HOMEPAGE_GALLERY_DELETE = 'HOMEPAGE_GALLERY_DELETE',
  HOMEPAGE_GALLERY_REORDER = 'HOMEPAGE_GALLERY_REORDER',
  HOMEPAGE_GALLERY_CREATE = 'HOMEPAGE_GALLERY_CREATE',

  // Category / Series
  CATEGORY_VIEW = 'CATEGORY_VIEW',
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_REORDER = 'CATEGORY_REORDER',
  CATEGORY_DELETE = 'CATEGORY_DELETE',

  // Featured Categories (6-tile homepage grid)
  FEATURED_CATEGORY_VIEW = 'FEATURED_CATEGORY_VIEW',
  FEATURED_CATEGORY_MANAGE = 'FEATURED_CATEGORY_MANAGE',

  // Products
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_SYNC = 'PRODUCT_SYNC',

  // CMS — Colors, Sizes, Variants, Materials
  CMS_VIEW = 'CMS_VIEW',
  CMS_COLOR_MANAGE = 'CMS_COLOR_MANAGE',
  CMS_SIZE_MANAGE = 'CMS_SIZE_MANAGE',
  CMS_VARIANT_MANAGE = 'CMS_VARIANT_MANAGE',
  CMS_MATERIAL_MANAGE = 'CMS_MATERIAL_MANAGE',
  CMS_STATIC_PAGE_MANAGE = 'CMS_STATIC_PAGE_MANAGE',
  CMS_TNC_MANAGE = 'CMS_TNC_MANAGE',
  CMS_PRIVACY_POLICY_MANAGE = 'CMS_PRIVACY_POLICY_MANAGE',
  CMS_EMAIL_TEMPLATE_MANAGE = 'CMS_EMAIL_TEMPLATE_MANAGE',

  // Blogs
  BLOG_CREATE = 'BLOG_CREATE',
  BLOG_UPDATE = 'BLOG_UPDATE',
  BLOG_DELETE = 'BLOG_DELETE',
  BLOG_CATEGORY_CREATE = 'BLOG_CATEGORY_CREATE',

  // Orders
  ORDER_VIEW = 'ORDER_VIEW',
  ORDER_UPDATE_STATUS = 'ORDER_UPDATE_STATUS',

  // Returns
  RETURN_VIEW = 'RETURN_VIEW',
  RETURN_MANAGE = 'RETURN_MANAGE',

  // Refunds
  REFUND_VIEW = 'REFUND_VIEW',
  REFUND_MANAGE = 'REFUND_MANAGE',

  // Coupons
  COUPON_CREATE = 'COUPON_CREATE',
  COUPON_READ = 'COUPON_READ',
  COUPON_UPDATE = 'COUPON_UPDATE',
  COUPON_DELETE = 'COUPON_DELETE',

  // Courier
  COURIER_VIEW = 'COURIER_VIEW',
  COURIER_MANAGE = 'COURIER_MANAGE',

  // Districts
  DISTRICT_MANAGE = 'DISTRICT_MANAGE',

  // Promo Banners
  BANNER_MANAGE = 'BANNER_MANAGE',

  // Flash Sales (curated campaign shown on the homepage + /sales)
  FLASH_SALE_MANAGE = 'FLASH_SALE_MANAGE',

  // Reviews
  REVIEW_MANAGE = 'REVIEW_MANAGE',

  // Tags
  TAG_CREATE = 'TAG_CREATE',

  // Barcodes
  BARCODE_VIEW = 'BARCODE_VIEW',
  BARCODE_CREATE = 'BARCODE_CREATE',
  BARCODE_UPDATE = 'BARCODE_UPDATE',

  // Locations
  LOCATION_VIEW = 'LOCATION_VIEW',
  LOCATION_CREATE = 'LOCATION_CREATE',

  //   company management
  COMPANY_MANAGE = 'COMPANY_MANAGE',

  // Fraud
  FRAUD_MANAGE = 'FRAUD_MANAGE',

  // Inventory
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_MANAGE = 'INVENTORY_MANAGE',

  // Suppliers
  SUPPLIER_VIEW = 'SUPPLIER_VIEW',
  SUPPLIER_MANAGE = 'SUPPLIER_MANAGE',

  // Partner API keys (3rd-party, read-only integrations)
  API_CLIENT_MANAGE = 'API_CLIENT_MANAGE',

  // Pieces (piece-level barcode tracking)
  PIECE_VIEW = 'PIECE_VIEW',
  PIECE_GENERATE = 'PIECE_GENERATE',
  PIECE_RECEIVE = 'PIECE_RECEIVE',
  PIECE_LOCATION_ASSIGN = 'PIECE_LOCATION_ASSIGN',
  PIECE_VOID = 'PIECE_VOID',

  // Reservations (Order Manager: reserve pieces, pick slip, pick-confirm)
  RESERVATION_MANAGE = 'RESERVATION_MANAGE',
  RESERVATION_PICK_CONFIRM = 'RESERVATION_PICK_CONFIRM',
  PICK_SLIP_VIEW = 'PICK_SLIP_VIEW',

  // Returns (Inventory Manager: scan a returned piece, mark good/damaged)
  RETURN_RECEIVE_SCAN = 'RETURN_RECEIVE_SCAN',

  // Piece inventory dashboard reporting
  DASHBOARD_SHELF_MAP_VIEW = 'DASHBOARD_SHELF_MAP_VIEW',
  DASHBOARD_DAMAGE_REPORT_VIEW = 'DASHBOARD_DAMAGE_REPORT_VIEW',

  // Payment methods (gateway/COD enable, fees, limits)
  PAYMENT_METHOD_VIEW = 'PAYMENT_METHOD_VIEW',
  PAYMENT_METHOD_MANAGE = 'PAYMENT_METHOD_MANAGE',

  // General settings (shipping defaults, etc.)
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',

  // Dashboard / Analytics (revenue, order, and traffic reporting)
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',

  // SEO metadata (per-URL title/description/schema records)
  SEO_MANAGE = 'SEO_MANAGE',

  // Support Tickets
  TICKET_VIEW = 'TICKET_VIEW',
  TICKET_REPLY = 'TICKET_REPLY',
  TICKET_ASSIGN = 'TICKET_ASSIGN',
  TICKET_MANAGE = 'TICKET_MANAGE',

  // Misc / Admin-only (no permission check needed — SUPERADMIN bypass handles it)
  // CLOUDINARY_SIGNATURE, ACTIVITY_LOG, PROFILE — see note below
}
