// src/permission/action.enum.ts

export enum Action {
  // Broad Banner
  UPDATE_BROAD_BANNER = 'UPDATE_BROAD_BANNER',
  CREATE_BROAD_BANNER = 'CREATE_BROAD_BANNER',
  DELETE_BROAD_BANNER = 'DELETE_BROAD_BANNER',

  // seasonal categories
  SEASONAL_CATEGORY_DELETE = 'SEASONAL_CATEGORY_DELETE',
  SEASONAL_CATEGORY_CREATE = 'SEASONAL_CATEGORY_CREATE',
  SEASONAL_CATEGORY_UPDATE = 'SEASONAL_CATEGORY_UPDATE',
  SEASONAL_CATEGORY_REORDER = 'SEASONAL_CATEGORY_REORDER',

  // seasonal categories
  HOMEPAGE_GALLERY_UPDATE = 'HOMEPAGE_GALLERY_UPDATE',
  HOMEPAGE_GALLERY_DELETE = 'HOMEPAGE_GALLERY_DELETE',
  HOMEPAGE_GALLERY_REORDER = 'HOMEPAGE_GALLERY_REORDER',
  HOMEPAGE_GALLERY_CREATE = 'HOMEPAGE_GALLERY_CREATE',

  // Category / Series
  CATEGORY_VIEW = 'CATEGORY_VIEW',
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_REORDER = 'CATEGORY_REORDER',

  // Products
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_SYNC = 'PRODUCT_SYNC',

  // CMS — Colors, Sizes, Variants, Materials
  CMS_VIEW = 'CMS_VIEW',
  CMS_COLOR_MANAGE = 'CMS_COLOR_MANAGE',
  CMS_SIZE_MANAGE = 'CMS_SIZE_MANAGE',
  CMS_VARIANT_MANAGE = 'CMS_VARIANT_MANAGE',
  CMS_MATERIAL_MANAGE = 'CMS_MATERIAL_MANAGE',

  // Blogs
  BLOG_CREATE = 'BLOG_CREATE',
  BLOG_UPDATE = 'BLOG_UPDATE',
  BLOG_DELETE = 'BLOG_DELETE',
  BLOG_CATEGORY_CREATE = 'BLOG_CATEGORY_CREATE',

  // Orders
  ORDER_VIEW = 'ORDER_VIEW',
  ORDER_UPDATE_STATUS = 'ORDER_UPDATE_STATUS',

  // Coupons
  COUPON_CREATE = 'COUPON_CREATE',
  COUPON_READ = 'COUPON_READ',
  COUPON_UPDATE = 'COUPON_UPDATE',
  COUPON_DELETE = 'COUPON_DELETE',

  // Courier
  COURIER_VIEW = 'COURIER_VIEW',
  COURIER_MANAGE = 'COURIER_MANAGE',

  // Districts
  DISTRICT_MANAGE = 'DISTRICT_MANAGE',

  // Promo Banners
  BANNER_MANAGE = 'BANNER_MANAGE',

  // Reviews
  REVIEW_MANAGE = 'REVIEW_MANAGE',

  // Tags
  TAG_CREATE = 'TAG_CREATE',

  // Barcodes
  BARCODE_VIEW = 'BARCODE_VIEW',
  BARCODE_CREATE = 'BARCODE_CREATE',
  BARCODE_UPDATE = 'BARCODE_UPDATE',

  // Locations
  LOCATION_VIEW = 'LOCATION_VIEW',
  LOCATION_CREATE = 'LOCATION_CREATE',

  //   company management
  COMPANY_MANAGE = 'COMPANY_MANAGE',

  // Fraud
  FRAUD_MANAGE = 'FRAUD_MANAGE',

  // Misc / Admin-only (no permission check needed — SUPERADMIN bypass handles it)
  // CLOUDINARY_SIGNATURE, ACTIVITY_LOG, PROFILE — see note below
}
