export enum UserRole {
  SUPERADMIN = 'SUPERADMIN',
  PRODUCTMANAGER = 'PRODUCTMANAGER',
  ORDERMANAGER = 'ORDERMANAGER',
  INVENTORYMANAGER = 'INVENTORYMANAGER',
  SUPPORT = 'SUPPORT',
  CUSTOMER = 'CUSTOMER',
}
